# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
    groups:
      charmbracelet:
        patterns:
          - "github.com/charmbracelet/*"
      muesli:
        patterns:
          - "github.com/muesli/*"
      spf13:
        patterns:
          - "github.com/spf13/*"
      golang-x:
        patterns:
          - "golang.org/x/*"
      testing:
        patterns:
          - "github.com/jarcoal/httpmock"
          - "github.com/stretchr/testify"
          - "gopkg.in/check.v1"
      gofiber:
        patterns:
          - "github.com/gofiber/*"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
