name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '❗ Breaking Changes'
    labels:
      - '❗ BreakingChange'
  - title: '🚀 New'
    labels:
      - '✏️ Feature'
      - '📝 Proposal'
  - title: '🧹 Updates'
    labels:
      - '🧹 Updates'
      - '⚡️ Performance'
  - title: '🐛 Fixes'
    labels:
      - '☢️ Bug'
  - title: '🛠️ Maintenance'
    labels:
      - '🤖 Dependencies'
  - title: '📚 Documentation'
    labels:
      - '📒 Documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - dependabot
  - dependabot[bot]
version-resolver:
  major:
    labels:
      - 'major'
      - '❗ BreakingChange'
  minor:
    labels:
      - 'minor'
      - '✏️ Feature'
      - '📝 Proposal'
  patch:
    labels:
      - 'patch'
      - '📒 Documentation'
      - '☢️ Bug'
      - '🤖 Dependencies'
      - '🧹 Updates'
      - '⚡️ Performance'
  default: patch
autolabeler:
    - label: '📒 Documentation'
      title:
          - '/docs/i'
          - '/doc:/i'
          - '/\[doc\]/i'
          - '/README/i'
          - '/typos/i'
          - '/comment/i'
          - '/📚/i'
          - '/📒/i'
          - '/📝/i'
          - '/documentation/i'
    - label: '☢️ Bug'
      title:
          - '/fix/i'
          - '/race/i'
          - '/bug/i'
          - '/missing/i'
          - '/correct/i'
          - '/🐛/i'
          - '/☢/i'
          - '/🩹/i'
          - '/🚨/i'
    - label: '🧹 Updates'
      title:
          - '/improve/i'
          - '/update/i'
          - '/refactor/i'
          - '/deprecated/i'
          - '/remove/i'
          - '/unused/i'
          - '/test/i'
          - '/⚡/i'
          - '/👷/i'
          - '/🚧/i'
          - '/♻️/i'
          - '/🎨/i'
          - '/🧪/i'
          - '/🧹/i'
    - label: '🤖 Dependencies'
      title:
          - '/bumb/i'
          - '/dependencies/i'
          - '/📦/i'
          - '/🤖/i'
    - label: '✏️ Feature'
      title:
          - '/feature/i'
          - '/create/i'
          - '/implement/i'
          - '/add/i'
          - '/🚀/i'
          - '/✨/i'
          - '/🔥/i'
template: |
    $CHANGES

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

    Thank you $CONTRIBUTORS for making this update possible.
