on: [push, pull_request]
name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Gosec
        uses: securego/gosec@v2
        with:          args: -exclude-dir=internal/*/ ./...

