on: [push, pull_request]
name: Test
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        cache-dependency-path: '**/go.sum'
    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest
    - name: Run Test
      run: |
        gotestsum --format standard-verbose -- -race ./...
