name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.25.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        cache-dependency-path: '**/go.sum'
    - name: Run Test
      uses: gofiber/.github/.github/actions/gotestsum@main
      with:
        packages: ./...
        rerun-fails: '2'
        args: -race -count=1 -coverprofile=coverage.txt -covermode=atomic -shuffle=on
