name: Test

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        cache-dependency-path: '**/go.sum'
    - name: Run Test
      run: |
        go run gotest.tools/gotestsum@latest -f testname -- ./... -race -count=1 -coverprofile=coverage.txt -covermode=atomic -shuffle=on
